Repository 0xPolygonZero/plonky2, pull requests merged in 2023-11, with the labels that each got.

#1260 Add context constraints
  evm/src/cpu/columns/mod.rs
  evm/src/cpu/contextops.rs
Labels: soundness

#1259 Combine JUMPDEST and KECCAK_GENERAL flags.
  evm/src/cpu/columns/ops.rs
  evm/src/cpu/control_flow.rs
  evm/src/cpu/decode.rs
  evm/src/cpu/gas.rs
  evm/src/cpu/stack.rs
  evm/src/witness/transition.rs
Labels: optimization

#1318 Constrain uninitialized memory to 0
  evm/src/memory/memory_stark.rs
Labels: bug, soundness

#1334 Remove `len` column in `KeccakSpongeStark`
  evm/src/keccak_sponge/columns.rs
  evm/src/keccak_sponge/keccak_sponge_stark.rs
Labels: optimization

#1327 Implement EIP-6780 (new SELFDESTRUCT)
  evm/src/cpu/kernel/asm/core/create_contract_account.asm
  evm/src/cpu/kernel/asm/core/selfdestruct_list.asm
  evm/src/cpu/kernel/asm/core/terminate.asm
  evm/src/cpu/kernel/asm/core/transfer.asm
  evm/src/cpu/kernel/asm/journal/account_created.asm
  evm/src/cpu/kernel/constants/global_metadata.rs
  evm/src/memory/segments.rs
Labels: cancun

#1168 Add memory checks for prover_input, as well as range_checks for prover_input, syscalls/exceptions
  evm/src/arithmetic/arithmetic_stark.rs
  evm/src/arithmetic/columns.rs
  evm/src/arithmetic/mod.rs
  evm/src/cpu/cpu_stark.rs
  evm/src/cpu/stack.rs
  evm/src/witness/operation.rs
  evm/src/witness/traces.rs
Labels: soundness

#1311 Create Poseidon tables
  evm/src/all_stark.rs
  evm/src/cpu/columns/ops.rs
  evm/src/cpu/contextops.rs
  evm/src/cpu/control_flow.rs
  evm/src/cpu/cpu_stark.rs
  evm/src/cpu/decode.rs
  evm/src/cpu/gas.rs
  evm/src/cpu/kernel/opcodes.rs
  evm/src/cpu/stack.rs
  evm/src/fixed_recursive_verifier.rs
  evm/src/lib.rs
  evm/src/poseidon/columns.rs
  evm/src/poseidon/mod.rs
  evm/src/poseidon/poseidon_stark.rs
  evm/src/prover.rs
  evm/src/verifier.rs
  evm/src/witness/gas.rs
  evm/src/witness/operation.rs
  evm/src/witness/traces.rs
  evm/src/witness/transition.rs
  evm/src/witness/util.rs
  evm/tests/empty_txn_list.rs
  evm/tests/log_opcode.rs
  plonky2/src/hash/poseidon.rs
Labels: type-2

#1343 Constrain clock
  evm/src/cpu/clock.rs
  evm/src/cpu/cpu_stark.rs
  evm/src/cpu/mod.rs
Labels: soundness

#1342 Range-check keccak sponge inputs to bytes
  evm/src/keccak_sponge/columns.rs
  evm/src/keccak_sponge/keccak_sponge_stark.rs
Labels: soundness

#1291 Remove values of last memory channel
  evm/src/all_stark.rs
  evm/src/cpu/bootstrap_kernel.rs
  evm/src/cpu/byte_unpacking.rs
  evm/src/cpu/columns/mod.rs
  evm/src/cpu/contextops.rs
  evm/src/cpu/cpu_stark.rs
  evm/src/cpu/decode.rs
  evm/src/cpu/docs/memory-handling.md
  evm/src/cpu/kernel/asm/account_code.asm
  evm/src/cpu/kernel/asm/core/call.asm
  evm/src/cpu/kernel/asm/core/create_receipt.asm
  evm/src/cpu/kernel/asm/core/exception.asm
  evm/src/cpu/kernel/asm/core/jumpdest_analysis.asm
  evm/src/cpu/kernel/asm/core/process_txn.asm
  evm/src/cpu/kernel/asm/core/syscall.asm
  evm/src/cpu/kernel/asm/core/terminate.asm
  evm/src/cpu/kernel/asm/curve/wnaf.asm
  evm/src/cpu/kernel/asm/memory/core.asm
  evm/src/cpu/kernel/asm/memory/memcpy.asm
  evm/src/cpu/kernel/asm/memory/memset.asm
  evm/src/cpu/kernel/asm/memory/metadata.asm
  evm/src/cpu/kernel/asm/memory/packing.asm
  evm/src/cpu/kernel/asm/memory/syscalls.asm
  evm/src/cpu/kernel/asm/shift.asm
  evm/src/cpu/kernel/asm/transactions/type_1.asm
  evm/src/cpu/kernel/asm/transactions/type_2.asm
  evm/src/cpu/kernel/interpreter.rs
  evm/src/cpu/kernel/opcodes.rs
  evm/src/cpu/membus.rs
  evm/src/cpu/memio.rs
  evm/src/cpu/mod.rs
  evm/src/cpu/shift.rs
  evm/src/cpu/stack.rs
  evm/src/cpu/syscalls_exceptions.rs
  evm/src/generation/mod.rs
  evm/src/generation/prover_input.rs
  evm/src/witness/gas.rs
  evm/src/witness/memory.rs
  evm/src/witness/operation.rs
  evm/src/witness/transition.rs
  evm/src/witness/util.rs
  evm/tests/empty_txn_list.rs
Labels: optimization

#1330 SMT deletion
  evm/src/cpu/kernel/aggregator.rs
  evm/src/cpu/kernel/asm/core/create.asm
  evm/src/cpu/kernel/asm/core/create_contract_account.asm
  evm/src/cpu/kernel/asm/core/terminate.asm
  evm/src/cpu/kernel/asm/core/util.asm
  evm/src/cpu/kernel/asm/journal/account_destroyed.asm
  evm/src/cpu/kernel/asm/journal/code_change.asm
  evm/src/cpu/kernel/asm/journal/nonce_change.asm
  evm/src/cpu/kernel/asm/journal/storage_change.asm
  evm/src/cpu/kernel/asm/mpt/delete/delete.asm
  evm/src/cpu/kernel/asm/mpt/storage/storage_write.asm
  evm/src/cpu/kernel/asm/smt/delete.asm
  evm/src/cpu/kernel/asm/smt/insert.asm
  evm/src/cpu/kernel/asm/smt/utils.asm
  evm/src/cpu/kernel/asm/transactions/common_decoding.asm
  evm/src/cpu/kernel/tests/smt/delete.rs
  evm/src/cpu/kernel/tests/smt/mod.rs
  evm/src/generation/mod.rs
  evm/src/generation/outputs.rs
  evm/src/generation/trie_extractor.rs
Labels: type-2

#1347 Refactor JUMPDEST analysis
  evm/src/cpu/kernel/asm/core/jumpdest_analysis.asm
Labels: optimization

#1352 Add push constraints
  evm/src/all_stark.rs
  evm/src/byte_packing/byte_packing_stark.rs
  evm/src/cpu/cpu_stark.rs
  evm/src/cpu/stack.rs
  evm/src/cross_table_lookup.rs
  evm/src/witness/operation.rs
  evm/tests/empty_txn_list.rs
  evm/tests/log_opcode.rs
Labels: soundness

#1357 Constrain is_keccak_sponge
  evm/src/cpu/bootstrap_kernel.rs
Labels: soundness

#1362 Update Memory in specs
  evm/spec/tables/memory.tex
  evm/spec/zkevm.pdf
Labels: documentation

#1355 Add doc for privileged instructions
  evm/spec/instructions.tex
  evm/spec/zkevm.pdf
  evm/spec/zkevm.tex
Labels: documentation

#1363 Update specs for Logic and Arithmetic Tables
  evm/spec/tables/arithmetic.tex
  evm/spec/tables/logic.tex
  evm/spec/zkevm.pdf
Labels: documentation

#1364 Reduce visibility
  evm/src/arithmetic/columns.rs
  evm/src/cpu/clock.rs
  evm/src/cpu/columns/general.rs
  evm/src/cpu/columns/mod.rs
  evm/src/cpu/columns/ops.rs
  evm/src/cpu/cpu_stark.rs
  evm/src/cpu/kernel/constants/exc_bitfields.rs
  evm/src/cpu/membus.rs
  evm/src/cpu/stack_bounds.rs
  evm/src/extension_tower.rs
  evm/src/keccak/columns.rs
  evm/src/keccak_sponge/columns.rs
  evm/src/logic.rs
  evm/src/memory/segments.rs
  evm/src/proof.rs
  evm/src/witness/memory.rs
Labels: bug

#1366 Add specs for KeccakSponge
  evm/spec/tables/keccak-sponge.tex
  evm/spec/zkevm.pdf
Labels: documentation

#1365 Update Keccak-f specs.
  evm/spec/tables/keccak-f.tex
  evm/spec/zkevm.pdf
Labels: documentation

#1368 CTL and range-check documentation
  evm/spec/framework.tex
  evm/spec/zkevm.pdf
Labels: documentation

#1372 Add exceptions to specs
  evm/spec/exceptions.tex
  evm/spec/zkevm.pdf
  evm/spec/zkevm.tex
  evm/src/cpu/kernel/asm/core/exception.asm
Labels: documentation

#1370 Initialize blockhashes
  evm/src/fixed_recursive_verifier.rs
  evm/src/proof.rs
  evm/tests/empty_txn_list.rs
Labels: bug

#1369 Check is_kernel_mode when halting
  evm/src/cpu/halt.rs
Labels: soundness

#1373 Add specs for BytePackingStark
  evm/spec/tables/byte-packing.tex
  evm/spec/zkevm.pdf
Labels: documentation

#1380 Add range check constraints for the looked table
  evm/src/byte_packing/byte_packing_stark.rs
  evm/src/keccak_sponge/keccak_sponge_stark.rs
  evm/src/memory/memory_stark.rs
Labels: soundness

#1378 Explain difference between simple opcodes and syscalls
  evm/spec/cpulogic.tex
  evm/spec/zkevm.pdf
Labels: documentation

#1375 Add specs for the CPU table
  evm/spec/tables/cpu.tex
  evm/spec/zkevm.pdf
Labels: documentation

#1379 Backporting gas handling to the specs
  evm/spec/cpulogic.tex
  evm/spec/zkevm.pdf
  evm/src/cpu/docs/out-of-gas.md
Labels: documentation

#1381 Add specs for stack handling
  evm/spec/cpulogic.tex
  evm/spec/zkevm.pdf
  evm/src/cpu/docs/memory-handling.md
Labels: documentation

#1382 Fix genesis block number in `prove_block`
  evm/src/fixed_recursive_verifier.rs
  evm/tests/empty_txn_list.rs
  evm/tests/log_opcode.rs
Labels: bug

#1351 Fix run_syscall in interpreter.
  evm/src/cpu/kernel/interpreter.rs
  evm/src/cpu/kernel/tests/account_code.rs
Labels: Interpreter

#1388 Remove extra rows in BytePackingStark
  evm/spec/tables/byte-packing.tex
  evm/spec/zkevm.pdf
  evm/src/byte_packing/byte_packing_stark.rs
  evm/src/byte_packing/columns.rs
  evm/src/witness/traces.rs
  evm/tests/empty_txn_list.rs
  evm/tests/log_opcode.rs
Labels: optimization

#1359 Changes in interpreter and implement interpreter version for add11
  evm/src/cpu/kernel/interpreter.rs
  evm/src/cpu/kernel/tests/account_code.rs
  evm/src/cpu/kernel/tests/add11.rs
  evm/src/cpu/kernel/tests/exp.rs
  evm/src/cpu/kernel/tests/mod.rs
  evm/src/cpu/kernel/tests/signed_syscalls.rs
Labels: Interpreter

#1360 Move stack_len_bounds_aux to general columns
  evm/spec/cpulogic.tex
  evm/spec/tables/cpu.tex
  evm/spec/zkevm.pdf
  evm/src/cpu/columns/general.rs
  evm/src/cpu/columns/mod.rs
  evm/src/cpu/cpu_stark.rs
  evm/src/cpu/kernel/interpreter.rs
  evm/src/cpu/mod.rs
  evm/src/cpu/stack.rs
  evm/src/cpu/stack_bounds.rs
  evm/src/witness/operation.rs
  evm/src/witness/state.rs
  evm/src/witness/transition.rs
  evm/src/witness/util.rs
Labels: optimization

#1384 Optimize `num_bytes` and `hex_prefix_rlp`
  evm/src/cpu/kernel/asm/mpt/hex_prefix.asm
  evm/src/cpu/kernel/asm/rlp/encode.asm
  evm/src/cpu/kernel/asm/rlp/num_bytes.asm
  evm/src/generation/prover_input.rs
  evm/src/witness/errors.rs
Labels: optimization
