Repository 0xPolygonZero/plonky2, pull requests merged in 2023-12, with the labels that each got.

#1400 Fix kernel codehash discrepancy
  evm/src/cpu/kernel/asm/mpt/hex_prefix.asm
  evm/src/cpu/kernel/tests/kernel_consistency.rs
  evm/src/cpu/kernel/tests/mod.rs
  evm/src/generation/mod.rs
Labels: bug

#1401 Fix set_context constraints
  evm/src/cpu/contextops.rs
Labels: bug, soundness

#1398 Use logUp for CTLs
  evm/spec/framework.tex
  evm/spec/zkevm.pdf
  evm/src/cross_table_lookup.rs
  evm/src/fixed_recursive_verifier.rs
  evm/src/keccak/keccak_stark.rs
  evm/src/recursive_verifier.rs
  evm/src/verifier.rs
Labels: optimization

#1404 Implement degree 2 filters
  evm/spec/framework.tex
  evm/spec/zkevm.pdf
  evm/src/arithmetic/arithmetic_stark.rs
  evm/src/byte_packing/byte_packing_stark.rs
  evm/src/cpu/cpu_stark.rs
  evm/src/cross_table_lookup.rs
  evm/src/keccak/keccak_stark.rs
  evm/src/keccak_sponge/keccak_sponge_stark.rs
  evm/src/logic.rs
  evm/src/memory/memory_stark.rs
  evm/src/prover.rs
Labels: optimization

#1409 Preinitialize all code segments
  evm/spec/tables/memory.tex
  evm/spec/zkevm.pdf
  evm/src/cpu/kernel/asm/account_code.asm
  evm/src/cpu/kernel/asm/core/call.asm
  evm/src/cpu/kernel/asm/core/process_txn.asm
  evm/src/cpu/kernel/asm/memory/syscalls.asm
  evm/src/generation/prover_input.rs
Labels: optimization

#1413 Use mstore_32bytes to optimize decode_int_given_len
  evm/src/cpu/kernel/asm/rlp/decode.asm
Labels: optimization

#1414 Merge MSTORE_32BYTES and MLOAD_32BYTES columns
  evm/src/cpu/byte_unpacking.rs
  evm/src/cpu/columns/ops.rs
  evm/src/cpu/contextops.rs
  evm/src/cpu/cpu_stark.rs
  evm/src/cpu/decode.rs
  evm/src/cpu/gas.rs
  evm/src/cpu/stack.rs
  evm/src/witness/transition.rs
Labels: optimization

#1419 Check that limbs after the length are 0
  evm/src/byte_packing/byte_packing_stark.rs
Labels: soundness

#1417 Merge `push` and `prover_input` flags
  evm/src/cpu/columns/ops.rs
  evm/src/cpu/contextops.rs
  evm/src/cpu/control_flow.rs
  evm/src/cpu/cpu_stark.rs
  evm/src/cpu/decode.rs
  evm/src/cpu/gas.rs
  evm/src/cpu/stack.rs
  evm/src/witness/transition.rs
Labels: optimization

#1415 Constrain MSTORE_32BYTES new offset limbs
  evm/src/cpu/byte_unpacking.rs
Labels: soundness

#1434 Constrain new top to loaded value in MLOAD_GENERAL
  evm/src/cpu/memio.rs
Labels: soundness

#1397 Constrain first offset of a segment
  evm/spec/tables/memory.tex
  evm/spec/zkevm.pdf
  evm/src/memory/memory_stark.rs
Labels: soundness

#1436 Constrain partial_channel
  evm/src/cpu/dup_swap.rs
  evm/src/cpu/jumps.rs
  evm/src/cpu/memio.rs
  evm/src/cpu/stack.rs
Labels: soundness
