Repository 0xPolygonZero/plonky2, pull requests merged in 2023-10, with the labels that each got.

#1280 Fix shift constraint
  evm/src/cpu/shift.rs
  evm/src/witness/operation.rs
Labels: bug

#1283 Make sure success is 0 in contract failure
  evm/src/cpu/kernel/asm/core/process_txn.asm
Labels: bug

#1306 Handle empty case for `memcpy_bytes`
  evm/src/cpu/kernel/asm/memory/memcpy.asm
  evm/src/cpu/kernel/asm/memory/memset.asm
Labels: bug

#1310 Add missing constraints for DUP/SWAP
  evm/src/cpu/dup_swap.rs
Labels: soundness

#1312 Implement EIP-5656 (MCOPY)
  evm/src/cpu/kernel/asm/core/exception.asm
  evm/src/cpu/kernel/asm/core/syscall.asm
  evm/src/cpu/kernel/asm/memory/syscalls.asm
  evm/src/cpu/kernel/interpreter.rs
  evm/src/witness/transition.rs
Labels: cancun

#1313 Implement BLOBBASEFEE
  evm/src/cpu/kernel/asm/core/exception.asm
  evm/src/cpu/kernel/asm/core/syscall.asm
  evm/src/cpu/kernel/asm/memory/metadata.asm
  evm/src/cpu/kernel/constants/exc_bitfields.rs
  evm/src/cpu/kernel/constants/global_metadata.rs
  evm/src/cpu/kernel/interpreter.rs
  evm/src/cpu/kernel/opcodes.rs
  evm/src/generation/mod.rs
  evm/src/proof.rs
  evm/src/recursive_verifier.rs
  evm/src/verifier.rs
  evm/src/witness/transition.rs
  evm/tests/add11_yml.rs
  evm/tests/basic_smart_contract.rs
  evm/tests/log_opcode.rs
  evm/tests/self_balance_gas_cost.rs
  evm/tests/simple_transfer.rs
Labels: cancun

#1292 Remerge context flags
  evm/src/cpu/columns/ops.rs
  evm/src/cpu/contextops.rs
  evm/src/cpu/control_flow.rs
  evm/src/cpu/decode.rs
  evm/src/cpu/gas.rs
  evm/src/cpu/memio.rs
  evm/src/cpu/stack.rs
  evm/src/witness/operation.rs
  evm/src/witness/transition.rs
Labels: optimization

#1257 Merge NOT and POP flags.
  evm/src/cpu/columns/ops.rs
  evm/src/cpu/control_flow.rs
  evm/src/cpu/decode.rs
  evm/src/cpu/gas.rs
  evm/src/cpu/simple_logic/not.rs
  evm/src/cpu/stack.rs
  evm/src/witness/operation.rs
  evm/src/witness/transition.rs
Labels: optimization

#1295 Add some documentation in EVM crate
  evm/spec/tables.tex
  evm/spec/tables/byte-packing.tex
  evm/spec/zkevm.pdf
  evm/src/all_stark.rs
  evm/src/arithmetic/addcy.rs
  evm/src/arithmetic/arithmetic_stark.rs
  evm/src/arithmetic/byte.rs
  evm/src/arithmetic/columns.rs
  evm/src/arithmetic/divmod.rs
  evm/src/arithmetic/mod.rs
  evm/src/arithmetic/modular.rs
  evm/src/arithmetic/mul.rs
  evm/src/arithmetic/shift.rs
  evm/src/arithmetic/utils.rs
  evm/src/byte_packing/byte_packing_stark.rs
  evm/src/byte_packing/columns.rs
  evm/src/byte_packing/mod.rs
  evm/src/cpu/bootstrap_kernel.rs
  evm/src/cpu/columns/general.rs
  evm/src/cpu/columns/mod.rs
  evm/src/cpu/columns/ops.rs
  evm/src/cpu/contextops.rs
  evm/src/cpu/control_flow.rs
  evm/src/cpu/cpu_stark.rs
  evm/src/cpu/decode.rs
  evm/src/cpu/dup_swap.rs
  evm/src/cpu/gas.rs
  evm/src/cpu/halt.rs
  evm/src/cpu/jumps.rs
  evm/src/cpu/membus.rs
  evm/src/cpu/memio.rs
  evm/src/cpu/modfp254.rs
  evm/src/cpu/pc.rs
  evm/src/cpu/push0.rs
  evm/src/cpu/shift.rs
  evm/src/cpu/simple_logic/eq_iszero.rs
  evm/src/cpu/simple_logic/mod.rs
  evm/src/cpu/simple_logic/not.rs
  evm/src/cpu/stack.rs
  evm/src/cpu/stack_bounds.rs
  evm/src/cpu/syscalls_exceptions.rs
  evm/src/cross_table_lookup.rs
  evm/src/keccak/keccak_stark.rs
  evm/src/keccak_sponge/columns.rs
  evm/src/keccak_sponge/keccak_sponge_stark.rs
  evm/src/logic.rs
  evm/src/memory/columns.rs
  evm/src/memory/memory_stark.rs
  evm/src/memory/mod.rs
  evm/src/proof.rs
  evm/src/prover.rs
  evm/src/vanishing_poly.rs
  evm/src/witness/operation.rs
Labels: documentation

#1256 Combine PUSH0 and PC flags.
  evm/src/cpu/columns/ops.rs
  evm/src/cpu/control_flow.rs
  evm/src/cpu/decode.rs
  evm/src/cpu/gas.rs
  evm/src/cpu/pc.rs
  evm/src/cpu/push0.rs
  evm/src/cpu/stack.rs
  evm/src/witness/transition.rs
Labels: optimization

#1317 Use `memcpy_bytes` whenever possible
  evm/src/cpu/kernel/asm/core/call.asm
  evm/src/cpu/kernel/asm/core/create.asm
  evm/src/cpu/kernel/asm/core/create_receipt.asm
  evm/src/cpu/kernel/asm/core/precompiles/id.asm
  evm/src/cpu/kernel/asm/core/precompiles/main.asm
  evm/src/cpu/kernel/asm/core/precompiles/rip160.asm
  evm/src/cpu/kernel/asm/core/precompiles/sha256.asm
  evm/src/cpu/kernel/asm/core/process_txn.asm
  evm/src/cpu/kernel/asm/core/terminate.asm
  evm/src/cpu/kernel/asm/rlp/encode_rlp_string.asm
  evm/src/cpu/kernel/asm/transactions/common_decoding.asm
  evm/src/cpu/kernel/asm/transactions/type_1.asm
  evm/src/cpu/kernel/asm/transactions/type_2.asm
Labels: optimization
