Repository 0xPolygonZero/plonky2, pull requests merged in 2024-01, with the labels that each got.

#1440 Add initial constraint z polynomial
  evm/src/lookup.rs
Labels: soundness

#1444 Add crate-level documentation
  evm/src/config.rs
  evm/src/fixed_recursive_verifier.rs
  evm/src/generation/mod.rs
  evm/src/lib.rs
  evm/tests/empty_txn_list.rs
  field/src/goldilocks_field.rs
  plonky2/src/fri/mod.rs
Labels: documentation

#1399 Refactor encode funcs
  evm/src/cpu/kernel/asm/main.asm
  evm/src/cpu/kernel/asm/mpt/hash/hash.asm
  evm/src/cpu/kernel/asm/mpt/hash/hash_trie_specific.asm
  evm/src/cpu/kernel/asm/mpt/util.asm
  evm/src/cpu/kernel/constants/global_metadata.rs
  evm/src/cpu/kernel/constants/mod.rs
  evm/src/cpu/kernel/interpreter.rs
  evm/src/memory/segments.rs
  evm/src/witness/memory.rs
Labels: optimization

#1453 Add Boolean constraints for `ArithmeticStark`
  evm/src/arithmetic/arithmetic_stark.rs
  evm/src/arithmetic/columns.rs
  evm/src/memory/memory_stark.rs
Labels: soundness

#1458 Constrain `syscall` / `exceptions` filter to be boolean
  evm/src/cpu/syscalls_exceptions.rs
Labels: soundness

#1447 Add some more explicit doc on plonky2 crate main components
  evm/src/curve_pairings.rs
  evm/src/lookup.rs
  plonky2/src/fri/mod.rs
  plonky2/src/gadgets/arithmetic.rs
  plonky2/src/gadgets/mod.rs
  plonky2/src/gates/arithmetic_base.rs
  plonky2/src/gates/arithmetic_extension.rs
  plonky2/src/gates/gate.rs
  plonky2/src/gates/mod.rs
  plonky2/src/gates/multiplication_extension.rs
  plonky2/src/hash/mod.rs
  plonky2/src/iop/ext_target.rs
  plonky2/src/iop/target.rs
  plonky2/src/lib.rs
  plonky2/src/plonk/circuit_builder.rs
  plonky2/src/plonk/circuit_data.rs
  plonky2/src/plonk/config.rs
  plonky2/src/plonk/mod.rs
  plonky2/src/plonk/plonk_common.rs
  plonky2/src/plonk/proof.rs
  plonky2/src/plonk/prover.rs
  plonky2/src/plonk/vanishing_poly.rs
  plonky2/src/plonk/vars.rs
  plonky2/src/plonk/verifier.rs
  plonky2/src/recursion/mod.rs
  plonky2/src/util/mod.rs
  plonky2/src/util/serialization/gate_serialization.rs
  plonky2/src/util/serialization/generator_serialization.rs
Labels: documentation

#1423 Refactor jumpdest analysis
  evm/src/cpu/kernel/asm/core/call.asm
  evm/src/cpu/kernel/asm/core/jumpdest_analysis.asm
  evm/src/cpu/kernel/asm/util/basic_macros.asm
  evm/src/cpu/kernel/interpreter.rs
  evm/src/cpu/kernel/tests/core/jumpdest_analysis.rs
  evm/src/generation/mod.rs
  evm/src/generation/prover_input.rs
  evm/src/generation/state.rs
  evm/src/generation/trie_extractor.rs
  evm/src/witness/errors.rs
  evm/tests/empty_txn_list.rs
Labels: optimization

#1450 Remove full memory channel
  evm/spec/zkevm.pdf
  evm/src/all_stark.rs
  evm/src/cpu/contextops.rs
  evm/src/cpu/cpu_stark.rs
  evm/src/cpu/dup_swap.rs
  evm/src/cpu/kernel/tests/add11.rs
  evm/src/cpu/membus.rs
  evm/src/cpu/memio.rs
  evm/src/cpu/shift.rs
  evm/src/cpu/syscalls_exceptions.rs
  evm/src/witness/operation.rs
Labels: optimization

#1460 Packed rlp prover inputs
  evm/src/cpu/kernel/asm/rlp/read_to_memory.asm
  evm/src/generation/rlp.rs
Labels: optimization

#1459 Add math rendering with Katex
  .cargo/katex-header.html
  evm/.cargo/katex-header.html
  evm/Cargo.toml
  field/.cargo/katex-header.html
  field/Cargo.toml
  maybe_rayon/.cargo/katex-header.html
  maybe_rayon/Cargo.toml
  plonky2/.cargo/katex-header.html
  plonky2/Cargo.toml
  plonky2/src/gates/coset_interpolation.rs
  plonky2/src/gates/gate.rs
  plonky2/src/gates/mod.rs
  starky/.cargo/katex-header.html
  starky/Cargo.toml
  util/.cargo/katex-header.html
  util/Cargo.toml
Labels: documentation

#1471 Fix interpreter jumps
  evm/src/cpu/kernel/interpreter.rs
Labels: bug

#1480 Improve SHA2 precompile
  evm/src/cpu/kernel/asm/hash/sha2/compression.asm
  evm/src/cpu/kernel/asm/hash/sha2/main.asm
  evm/src/cpu/kernel/asm/hash/sha2/message_schedule.asm
  evm/src/cpu/kernel/asm/hash/sha2/write_length.asm
  evm/src/cpu/kernel/asm/memory/core.asm
Labels: optimization

#1477 Improve `blake2f` call
  evm/src/cpu/kernel/asm/hash/blake2/addresses.asm
  evm/src/cpu/kernel/asm/hash/blake2/blake2_f.asm
  evm/src/cpu/kernel/asm/hash/blake2/g_functions.asm
  evm/src/cpu/kernel/asm/hash/blake2/hash.asm
Labels: optimization

#1476 Speed-up `bn254` pairing operation
  evm/src/cpu/kernel/asm/curve/bn254/curve_arithmetic/final_exponent.asm
  evm/src/cpu/kernel/asm/curve/bn254/curve_arithmetic/miller_loop.asm
  evm/src/cpu/kernel/asm/curve/bn254/curve_arithmetic/pairing.asm
  evm/src/cpu/kernel/asm/curve/bn254/field_arithmetic/inverse.asm
  evm/src/cpu/kernel/asm/curve/bn254/field_arithmetic/util.asm
Labels: optimization

#1482 Improve `BIGNUM` operations
  evm/src/cpu/kernel/asm/bignum/add.asm
  evm/src/cpu/kernel/asm/bignum/addmul.asm
  evm/src/cpu/kernel/asm/bignum/cmp.asm
  evm/src/cpu/kernel/asm/bignum/modmul.asm
  evm/src/cpu/kernel/asm/bignum/mul.asm
  evm/src/cpu/kernel/asm/bignum/shr.asm
  evm/src/cpu/kernel/asm/bignum/util.asm
  evm/src/cpu/kernel/asm/hash/blake2/addresses.asm
  evm/src/cpu/kernel/asm/hash/sha2/compression.asm
  evm/src/cpu/kernel/asm/hash/sha2/main.asm
  evm/src/cpu/kernel/asm/hash/sha2/message_schedule.asm
  evm/src/cpu/kernel/asm/hash/sha2/write_length.asm
  evm/src/cpu/kernel/asm/memory/core.asm
  evm/src/cpu/kernel/asm/util/basic_macros.asm
  evm/src/generation/prover_input.rs
Labels: optimization

#1474 Fix bugs in jumpdest analysis
  evm/src/cpu/kernel/asm/core/jumpdest_analysis.asm
  evm/src/cpu/kernel/interpreter.rs
  evm/src/cpu/kernel/tests/core/jumpdest_analysis.rs
  evm/src/generation/mod.rs
  evm/src/generation/prover_input.rs
  evm/src/generation/state.rs
Labels: bug
